Boilerplate project starter code for alpha watch face sample.
android/wear-os-samples pull request #65
Opened 2020-12-09 21:18 UTC by codingjeremy

This is boilerplate only for the alpha project. 

I was originally going to develop the Kotlin watch face sample to be the alpha sample, but I decided to separate them, so we have a production version kotlin version as well.

This will be the alpha version and folded into the regular kotlin version (WatchFaceKotlin) once the library exits beta.

2020-12-10 10:23 UTC, JolandaVerhoef approved these changes

2020-12-10 16:56 UTC, tiembo requested changes
Overall LGTM, some minor nits.

Also, do we want the explicit "alpha" designation in the app name (versus just calling out in the README that alpha libs are being used and naming the app something like "WatchFace (Kotlin)"?

2020-12-10 16:56 UTC, tiembo commented on WatchFaceAlphaKotlin/README.md
> +Demonstrates watch faces using the new androidx alpha libraries (Kotlin).
androidx => AndroidX

2020-12-10 16:56 UTC, tiembo commented on WatchFaceAlphaKotlin/README.md
> +With the release of the androidx alpha watch face libraries (late 2020), Wear OS has simplified
androidx => AndroidX

2020-12-10 16:56 UTC, tiembo commented on WatchFaceAlphaKotlin/README.md
> +this will allow runs.
clarify "this will allow runs"

2020-12-10 16:56 UTC, tiembo commented on WatchFaceAlphaKotlin/app/proguard-rules.pro
> +# Copyright (C) 2020 The Android Open Source Project
remove file if unused

2020-12-16 22:22 UTC, tiembo approved these changes

2020-12-17 22:43 UTC, merged